import {
  MetricItem,
  ClientLogo,
  EnterpriseEdgeItem,
  CatStage,
  DomainItem,
  CourseItem,
  TrainingProcessStep,
  TestimonialItem,
  FAQItem,
} from "@/types";

export const TRACK_RECORD_DATA: MetricItem[] = [
  {
    id: "learners",
    label: "Enterprise Learners",
    value: 10000,
    suffix: "+",
    subtext: "Upskilled across Fortune 500 & tech leaders",
    icon: "Users",
  },
  {
    id: "partners",
    label: "Corporate Partners",
    value: 200,
    suffix: "+",
    subtext: "Global enterprise clients transformed",
    icon: "Building2",
  },
  {
    id: "leadership",
    label: "Executive Leaders",
    value: 5000,
    suffix: "+",
    subtext: "Mid to senior executive leaders trained",
    icon: "Award",
  },
  {
    id: "satisfaction",
    label: "Program Completion Rate",
    value: 98,
    suffix: "%",
    subtext: "Highest retention & ROI in enterprise L&D",
    icon: "TrendingUp",
  },
];

export const CLIENT_LOGOS: ClientLogo[] = [
  { id: "1", name: "Reliance Industries", logoText: "RELIANCE", category: "Conglomerate", badge: "Strategic Partner" },
  { id: "2", name: "HCL Tech", logoText: "HCL TECH", category: "IT & Services" },
  { id: "3", name: "IBM Global Enterprise", logoText: "IBM", category: "Cloud & AI", badge: "Fortune 50" },
  { id: "4", name: "CRIF High Mark", logoText: "CRIF", category: "Fintech & Credit" },
  { id: "5", name: "ADP Employer Services", logoText: "ADP", category: "HR Tech & Payroll" },
  { id: "6", name: "Bayer Pharmaceuticals", logoText: "BAYER", category: "Healthcare & Biotech", badge: "Global" },
  { id: "7", name: "Deloitte Digital", logoText: "DELOITTE", category: "Consulting" },
  { id: "8", name: "Microsoft Enterprise", logoText: "MICROSOFT", category: "Cloud Infrastructure" },
  { id: "9", name: "Snowflake", logoText: "SNOWFLAKE", category: "Data Cloud" },
  { id: "10", name: "AWS Enterprise Solutions", logoText: "AWS", category: "Cloud Computing" },
];

export const ENTERPRISE_EDGE_DATA: EnterpriseEdgeItem[] = [
  {
    id: "tailored",
    stepNumber: "01",
    title: "Tailored Solutions",
    description: "Tailor-made curricula aligned precisely with your organization's OKRs, legacy tech stack, and strategic growth targets.",
    icon: "Sparkles",
    metrics: "100% Customized Content",
  },
  {
    id: "framework",
    stepNumber: "02",
    title: "Innovative Framework",
    description: "Proprietary CAT (Concept, Application, Tools) methodology ensuring seamless skill adoption from theory to production.",
    icon: "Boxes",
    metrics: "3.5x Faster Mastery",
  },
  {
    id: "offerings",
    stepNumber: "03",
    title: "Diverse Offerings",
    description: "From Generative AI and Data Science to Product Leadership and Executive Tech Strategy across all enterprise tiers.",
    icon: "Layers",
    metrics: "25+ Enterprise Tracks",
  },
  {
    id: "delivery",
    stepNumber: "04",
    title: "Flexible Delivery",
    description: "Hybrid execution models combining cohort live bootcamps, asynchronous micro-modules, and hands-on capstone labs.",
    icon: "Clock",
    metrics: "99.4% On-time Schedule",
  },
];

export const CAT_FRAMEWORK_DATA: CatStage[] = [
  {
    id: "concept",
    title: "Concept",
    subtitle: "Foundational Knowledge for Deep Mastery",
    description: "Master first-principles engineering and business concepts taught by industry veterans from Google, Amazon, and McKinsey.",
    icon: "Lightbulb",
    deliverables: [
      "Architectural Blueprint Mapping",
      "Executive Case Studies & Strategic Frameworks",
      "Interactive Knowledge Assessment Checkpoints",
    ],
    toolsList: ["Miro", "Notion Enterprise", "System Architecture Boards"],
    metrics: "100% Theoretical Grounding",
  },
  {
    id: "application",
    title: "Application",
    subtitle: "Practical Real-World Sandbox Labs",
    description: "Bridge theory and practice by solving live enterprise scenarios, simulating real production incidents and strategy sprints.",
    icon: "Terminal",
    deliverables: [
      "Production-Ready Code Repositories",
      "Live Enterprise Capstone Simulation",
      "Peer Code Reviews & Architecture Audits",
    ],
    toolsList: ["GitHub Enterprise", "Docker", "VS Code Cloud", "Jira"],
    metrics: "85% Hands-on Application",
  },
  {
    id: "tools",
    title: "Tools & Automation",
    subtitle: "Cutting-Edge Tech Stack Fluency",
    description: "Empower teams with state-of-the-art AI, Analytics, Cloud, and Product platforms used by market-leading tech companies.",
    icon: "Wrench",
    deliverables: [
      "Custom Enterprise Workflow Pipelines",
      "GenAI Agent Prompt & RAG Integration Templates",
      "Automated Continuous Integration Deployments",
    ],
    toolsList: ["OpenAI API", "Python Data Stack", "LangChain", "Kubernetes", "Tableau"],
    metrics: "10+ Tool Integrations",
  },
];

export const DOMAIN_EXPERTISE_DATA: DomainItem[] = [
  {
    id: "product",
    title: "Product & Innovation Hub",
    tagline: "Drive Product Lifecycle Excellence",
    description: "Empower product managers to build, scale, and monetize market-defining products using modern discovery and growth frameworks.",
    icon: "Layout",
    learners: "2,400+ Graduates",
    programsCount: 6,
    keySkills: ["Product Strategy", "User Research & Discovery", "Growth Metrics", "Agile Roadmap"],
  },
  {
    id: "gen-ai",
    title: "Gen-AI Mastery",
    tagline: "Enterprise AI & LLM Implementation",
    description: "Accelerate organizational AI maturity with RAG pipelines, fine-tuning, prompt engineering, and governance for enterprise scale.",
    icon: "Cpu",
    learners: "3,800+ Engineers",
    programsCount: 8,
    keySkills: ["LLM Architecture", "RAG Systems", "Vector DBs", "AI Ethics & Guardrails"],
  },
  {
    id: "leadership",
    title: "Leadership Elevation",
    tagline: "C-Suite & Executive Growth",
    description: "Transform senior managers into visionary leaders capable of navigating digital disruption, AI strategy, and team alignment.",
    icon: "ShieldCheck",
    learners: "1,900+ Directors",
    programsCount: 5,
    keySkills: ["Digital Transformation", "Executive Communication", "Change Leadership", "Strategic OKRs"],
  },
  {
    id: "tech-data",
    title: "Tech & Data Insights",
    tagline: "Data-Driven Enterprise Decisions",
    description: "Turn complex data ecosystems into actionable competitive insights with advanced analytics, ML engineering, and cloud data warehouses.",
    icon: "BarChart3",
    learners: "3,100+ Data Pros",
    programsCount: 7,
    keySkills: ["Data Engineering", "Predictive Analytics", "Snowflake / Databricks", "ML Ops"],
  },
  {
    id: "ops-ex",
    title: "Operations Excellence",
    tagline: "Lean Processes & Automation",
    description: "Optimize enterprise workflows, eliminate bottlenecks, and build resilient supply chains using process mining and automation.",
    icon: "Settings",
    learners: "1,500+ Ops Managers",
    programsCount: 4,
    keySkills: ["Workflow Automation", "Six Sigma", "Supply Chain Resiliency", "Process Mining"],
  },
  {
    id: "digital-ent",
    title: "Digital Enterprise",
    tagline: "Modern Cloud & DevSecOps",
    description: "Modernize legacy monoliths into cloud-native microservices with robust security compliance and CI/CD pipelines.",
    icon: "Globe",
    learners: "2,200+ Architects",
    programsCount: 6,
    keySkills: ["Cloud Architecture", "DevSecOps", "Microservices", "Zero-Trust Security"],
  },
  {
    id: "fintech",
    title: "Fintech Innovation Lab",
    tagline: "Next-Gen Financial Systems",
    description: "Master modern payment rails, open banking APIs, fraud prevention models, and decentralized ledger technologies.",
    icon: "Coins",
    learners: "1,100+ Analysts",
    programsCount: 4,
    keySkills: ["Payment Gateways", "Risk Modeling", "Open Banking APIs", "Regulatory Compliance"],
  },
];

export const COURSES_DATA: CourseItem[] = [
  {
    id: "c1",
    title: "Executive Post Graduate Program in GenAI & Product Architecture",
    category: "program",
    categoryLabel: "Program Specific",
    subtitle: "10-Month Executive Certification",
    description: "Designed for senior tech leaders and product heads ready to pioneer enterprise AI transformation.",
    duration: "10 Months",
    mode: "Live Online + Hybrid Sprints",
    badge: "Flagship Program",
    targetAudience: "VP Product, CTO, Senior Directors, Principal Engineers",
    highlights: [
      "Build live enterprise RAG applications",
      "Executive mentorship by Silicon Valley CTOs",
      "Comprehensive AI Capstone project with real company dataset",
    ],
    syllabus: [
      { title: "Module 1: Enterprise AI Foundations", duration: "2 Months", topics: ["LLM Fundamentals", "Transformer Architectures", "Prompt Engineering"] },
      { title: "Module 2: RAG & Vector Search Engineering", duration: "3 Months", topics: ["LangChain & LlamaIndex", "Pinecone & Qdrant", "Hybrid Search Tuning"] },
      { title: "Module 3: AI Product Leadership & Governance", duration: "3 Months", topics: ["AI Monetization", "Ethics & Bias", "Security & Guardrails"] },
      { title: "Module 4: Capstone Launch", duration: "2 Months", topics: ["Boardroom Presentation", "Production Deployment"] },
    ],
  },
  {
    id: "c2",
    title: "Fintech & Digital Banking Transformation Sprint",
    category: "industry",
    categoryLabel: "Industry Specific",
    subtitle: "Financial Services Accelerator",
    description: "Specialized curriculum for banking institutions migrating to cloud-native microservices and open banking.",
    duration: "3 Months",
    mode: "Cohort Live",
    badge: "Industry Favorite",
    targetAudience: "Banking Executives, Risk Officers, Tech Leads",
    highlights: [
      "Open Banking API standards compliance",
      "Real-time fraud prevention ML models",
      "Core banking modern architecture",
    ],
    syllabus: [
      { title: "Module 1: Modern Payment Protocols", duration: "1 Month", topics: ["ISO 20022", "Real-Time Payments", "API Security"] },
      { title: "Module 2: Fraud & Risk Machine Learning", duration: "1 Month", topics: ["Anomaly Detection", "Credit Risk Analytics"] },
      { title: "Module 3: Regulatory Compliance Architecture", duration: "1 Month", topics: ["GDPR / PCI-DSS", "Auditability in Cloud"] },
    ],
  },
  {
    id: "c3",
    title: "Advanced Data Engineering & Lakehouse Strategy",
    category: "topic",
    categoryLabel: "Topic Specific",
    subtitle: "Data Stack Mastery",
    description: "Deep dive into Snowflake, Databricks, dbt, and automated ETL/ELT data pipelines.",
    duration: "4 Months",
    mode: "Self-Paced + Live Mentorship",
    badge: "High Demand",
    targetAudience: "Data Engineers, Analytics Engineers, Database Admins",
    highlights: [
      "Hands-on dbt Cloud transformation pipelines",
      "Snowflake optimization & cost control",
      "Streaming ingestion with Apache Kafka",
    ],
    syllabus: [
      { title: "Module 1: Lakehouse Architecture Patterns", duration: "1 Month", topics: ["Delta Lake vs Iceberg", "Data Mesh Design"] },
      { title: "Module 2: Automated Modeling with dbt", duration: "1.5 Months", topics: ["Modular Data Modeling", "Testing & Documentation"] },
      { title: "Module 3: Real-Time Stream Processing", duration: "1.5 Months", topics: ["Kafka Streams", "Spark Streaming"] },
    ],
  },
  {
    id: "c4",
    title: "Senior Leadership & AI Acceleration Workshop",
    category: "level",
    categoryLabel: "Level Specific",
    subtitle: "C-Suite Intensive",
    description: "Concise 6-week intensive for non-technical executives seeking to evaluate, invest in, and steer AI initiatives.",
    duration: "6 Weeks",
    mode: "Weekend Executive Immersion",
    badge: "Executive Tier",
    targetAudience: "CEOs, CMOs, CFOs, Board Members",
    highlights: [
      "Calculating Enterprise AI ROI",
      "Vendor Evaluation Matrix (Open Source vs Proprietary)",
      "Organizational Change Management",
    ],
    syllabus: [
      { title: "Week 1-2: AI Landscape & ROI Blueprint", duration: "2 Weeks", topics: ["GenAI Tech Map", "Cost vs Benefit Calculator"] },
      { title: "Week 3-4: Risk & Regulatory Governance", duration: "2 Weeks", topics: ["IP Rights in AI", "Enterprise Security Standards"] },
      { title: "Week 5-6: Executive Strategic Action Plan", duration: "2 Weeks", topics: ["Talent Strategy", "100-Day AI Roadmap"] },
    ],
  },
];

export const TRAINING_PROCESS_DATA: TrainingProcessStep[] = [
  {
    step: 1,
    title: "Skill Gap Analysis & Alignment",
    subtitle: "Diagnosis & Discovery",
    description: "We conduct deep diagnostic audits of your engineering, product, and leadership talent to identify competency gaps against industry benchmarks.",
    icon: "SearchCheck",
    keyOutputs: ["Comprehensive Skills Heatmap", "Custom ROI Projections", "Tailored Program Roadmap"],
  },
  {
    step: 2,
    title: "Customized Training Plan",
    subtitle: "Curriculum Co-Creation",
    description: "Our instructional designers craft a bespoke curriculum using your enterprise codebases, real business cases, and internal toolsets.",
    icon: "FileCode2",
    keyOutputs: ["Proprietary Sandbox Environments", "Executive Mentorship Schedule", "Role-Based Modules"],
  },
  {
    step: 3,
    title: "Flexible Program Delivery & Impact Tracking",
    subtitle: "Execution & ROI Audit",
    description: "Multi-modal execution with real-time analytics dashboards for HR and L&D leaders to track completion rates, project scores, and skill acceleration.",
    icon: "Rocket",
    keyOutputs: ["Executive Dashboard Access", "Certified Capstone Submissions", "Post-Training ROI Report"],
  },
];

export const TESTIMONIALS_DATA: TestimonialItem[] = [
  {
    id: "t1",
    author: "Vikram Sharma",
    role: "Chief Technology Officer",
    company: "HCL Tech",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200",
    quote: "Accredian Enterprise transformed our senior engineering organization. Over 450 engineers completed the Gen-AI & Cloud Architecture track, reducing our product time-to-market by 38%.",
    rating: 5,
    category: "Technology",
    impactMetric: "38% Faster Time-to-Market",
  },
  {
    id: "t2",
    author: "Priya Nair",
    role: "VP of Global Learning & Development",
    company: "Reliance Industries",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200",
    quote: "The CAT framework is a game-changer. Our leaders didn't just learn theoretical concepts — they built real production-grade data pipelines that we deployed immediately.",
    rating: 5,
    category: "Leadership",
    impactMetric: "100% Capstone Deployment",
  },
  {
    id: "t3",
    author: "David Chen",
    role: "Head of Product Innovation",
    company: "ADP Enterprise",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200",
    quote: "Working with Accredian allowed us to upskill 1,200 product managers across 4 continents seamlessly. The customized course segmentation fit every level of our team.",
    rating: 5,
    category: "Product Management",
    impactMetric: "1,200+ PMs Upskilled",
  },
  {
    id: "t4",
    author: "Ananya Deshmukh",
    role: "Director of Enterprise AI",
    company: "IBM Software",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200",
    quote: "The rigor of Accredian's faculty and practical sandbox labs is unmatched. Their customized enterprise training is the standard for high-growth tech firms.",
    rating: 5,
    category: "Artificial Intelligence",
    impactMetric: "99.2% Retention Rate",
  },
];

export const FAQ_DATA: FAQItem[] = [
  {
    id: "faq-1",
    question: "How does Accredian Enterprise customize curricula for our specific industry?",
    answer: "Our instructional design team conducts an upfront diagnostic audit of your team's codebases, business goals, and current skill matrix. We then adapt our foundational modules to incorporate your company's actual datasets, internal tools, and architectural guidelines.",
    category: "Curricula",
  },
  {
    id: "faq-2",
    question: "What is the typical team size and structure for enterprise training cohort?",
    answer: "We support cohort sizes ranging from dedicated pods of 15-20 senior leaders up to enterprise-wide programs upskilling 5,000+ employees simultaneously across time zones.",
    category: "Enterprise Setup",
  },
  {
    id: "faq-3",
    question: "What security measures and data privacy protocols are enforced in sandbox environments?",
    answer: "All sandbox labs run in SOC-2 Type II compliant, isolated cloud environments. We never store or expose your proprietary enterprise data, and single sign-on (SSO / SAML 2.0) is built-in.",
    category: "Security & ROI",
  },
  {
    id: "faq-4",
    question: "How do L&D managers measure ROI and employee skill progression?",
    answer: "Enterprise clients get access to an Executive Analytics Dashboard featuring real-time attendance, project submission scores, skill gap reduction metrics, and post-graduation capstone impact reports.",
    category: "Security & ROI",
  },
  {
    id: "faq-5",
    question: "What format are the programs delivered in (Live vs Self-paced)?",
    answer: "We offer flexible hybrid delivery: live cohort sessions hosted by top industry faculty, coupled with self-paced micro-modules, interactive coding sandboxes, and weekend executive masterclasses.",
    category: "General",
  },
  {
    id: "faq-6",
    question: "Can we integrate Accredian Enterprise with our internal LMS (e.g. Workday, Cornerstone)?",
    answer: "Yes, Accredian seamlessly integrates with major enterprise LMS solutions via SCORM / xAPI / LTI standards and automated SSO user provisioning.",
    category: "Enterprise Setup",
  },
];
